### ISSUE TITLE
CSS Logical Properties shouldn't be used as fallback

### ISSUE THREAD

**Issue by mdizo** [stormwarning/stylelint-config-recess-order#299]
CSS logical properties are currently ordered before their conventional counterparts when it should be the other way around because of CSS' cascading nature.

Logical properties should be placed later so that if the browser doesn't support the property then it will fallback to the normal properties.

**Comment by kutsan** [comment]
[stylelint-config-clean-order](https://github.com/kutsan/stylelint-config-clean-order) includes your changes and you can use it instead of `recess-order`. I made my config since this one looks unmaintained.

**Comment by stormwarning** [comment]
Hmm, I was thinking about it more like the logical properties are less "specific", similar to how shorthand properties like `margin` come before more specific ones like `margin-left` — something could be `inline-start` in general but need to be `right` no matter what the writing mode is.

Not shutting down the suggestion, but I'll leave this open for other feedback since it'd be a breaking change.
